version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
    groups:
      packages:
        patterns:
          - "*"
